### ISSUE TITLE
Is there a place for inherently divisive channels on ZATech?

### ISSUE THREAD

**Issue by n1c** [zatech/code-of-conduct#34] opened 2021-08-03 11:52 UTC
Over time the admins have had a difficult time moderating the discussions in inherently divisive channels, specifically #covid (now closed), #politics & #politics-za.

It seems as though because there is very often (understandably) conflicting views on topics discussed in those channels, there will always be tension. This tension inevitably requires the involvement of admins, and if I'm honest this involvement isn't done in a consistent way. It's a shit job having to be the janitor or fun police.

The idea that the solution to this problem is more people get warned, banned, or the nitty gritty or messaging and wording should constantly be managed and unravelled by a group of admins feels like a dead end. Even in the admin group there is often very little alignment on the issues. We all have very different life/world/political/religious etc. views and that is a good thing. 

Personally I don't believe that there's any value in having those discussions exist on a platform that is intended to be for the professional discussion of technology. I think it's no secret that I've often fought for the group as a whole to be more tech focused, and the closure of noisier off-topic channels. I wouldn't be surprised if I end up writing a similar message in a few months calling for the closure of #random or similar (#32 needs resolving).

For now I think it's time for us to seriously consider that there is no place for public political discussion on the platform. This isn't anyone's personal debate club and there are many other places people can go to do such. We just don't have the systems or energy to manage it in a way that is even close to fair on ZATech.

Please let me know here if there are arguments for keeping the discussions and channels alive.

**Comment by CannibalKush** [comment] 2021-08-03 14:04
LGTM 🪓

**Comment by zkrige** [comment] 2021-08-03 14:05
@n1c firstly - let me say that I think everyone appreciates the work you do and having to babysit a bunch of cry babies doesn't sound like much fun.

Another option is to leave those channels unmoderated and not tolerate any complaints emanating from there? My thinking is that there are already private channels (eg #covid-private) and you don't accept complaints from there

**Comment by William-Francis** [comment] 2021-08-03 14:55
I also appreciate the hard work the admins put in, and understand the difficult situation those channels cause. I personally find those channels valuable.
One potential problem could be that removing those channels might cause spillover into other channels (similar to covid talk which still shows its head in strange places).

Maybe a stricter set of rules for those channels? like no sarcasm/bad faith arguments?

**Comment by fardarter** [comment] 2021-08-03 15:15
I agree with @William-Francis here. I find value in these channels. 

I also believe, and have said many times, that stricter discourse norms for keeping debate productive would help. 

I think enforcing the charity requirement in discussions would go a long way. 

For example, it's not charitable to assume that because someone likes a redistributive policy that they're endorsing Stalinist purges.

**Comment by mobiRic** [comment] 2021-08-03 15:53
If you remove the channels, I see one of three things happening:
1. ppl use the other channels continuously to fight (that's an obvious one, and you've seen it happen many times)
2. ppl make private channels and the whole discoverability of zatech goes out the window - that new #private-channel-directory is not going to solve that imho
3. ppl just leave because you will have destroyed a vibrant part of your community - then you have a dead slack

**Comment by pvtmonkey** [comment] 2021-08-03 17:26
Let it burn yo. Please delete cape town too. 90% of the entire platform is a debate club anyways, if not that memes. I guess job posting is going strong though. Pretty much agreed that half the moderation on zatech is not fairly managed, mods either miss half the messages because they're busy or burnout. Next step is the private channels to become riddled with conflict, but are unmoderated and reputation sinks even lower because divisiveness becomes unmanaged and people kick each other twice a day like Fardarter and BOFH who have irreconcilable differences.

**Comment by fardarter** [comment] 2021-08-03 17:51
@n1c "90% of the entire platform is a debate club anyways,"

I'm not sure if the above is true, but I certainly come to ZATech to hang out with other developers more than for tech Q&A or job postings, as useful as those are.

Like @mobiRic, I feel that the non-tech channels are part of what makes ZATech a community.

**Comment by mrMonkey2020** [comment] 2021-08-03 17:58
![image](https://user-images.githubusercontent.com/88397494/128063512-689f0b10-858b-4992-afe9-53e750bbf087.png)

**Comment by mrMonkey2020** [comment] 2021-08-03 18:53
Let the haters be the wings beneath your wings

**Comment by n1c** [comment] 2021-08-04 06:51
> Another option is to leave those channels unmoderated and not tolerate any complaints emanating from there? My thinking is that there are already private channels (eg #covid-private) and you don't accept complaints from there

> Maybe a stricter set of rules for those channels? like no sarcasm/bad faith arguments?

> I think enforcing the charity requirement in discussions would go a long way.

There's no problem with the current set of rules for the group. The problem is enforcement. I also don't think this is necessarily a solvable thing because the issues are predominantly subjective things where whichever side of the problem the admin falls personally will get the attention. That's bad and is the point of this post, "inherently divisive channels" will always have this problem. If all the admins had the same set of beliefs that would just get enforced and be what the whole group believes, but I don't think that's productive.

It seems like trying to move politics discussion into private channels has potential, though like Ric points out there's a few pretty likely negative outcomes there.

@mrMonkey2020 please don't use an alt to try engage in good faith conversation. I'm going to block your account and if you'd like to interact here do so properly.

**Comment by mrMonkey2020** [comment] 2021-08-04 07:09
lol way to ignore valid points, I'm out and said everything I've needed :v:

**Comment by ChristianWitts** [comment] 2021-08-04 09:25
>     3. ppl just leave because you will have destroyed a vibrant part of your community - then you have a dead slack

To directly address this @mobiRic, lots of good people have left the slack because of certain channels that have contributed to 90%+ of the divisiveness. I'd prefer to have them back, than people who leave because they can longer spit vitriol with near impunity.

**Comment by mobiRic** [comment] 2021-08-04 09:25
It is sad that your team asked for input, and someone gave honest feedback and got banned for doing it. No wonder they felt they had to create an alt (and were quite honest about it) to participate - imagine if you'd just banned their real persona from github .

**Comment by zeorin** [comment] 2021-08-04 16:19
My opinion is that all tech is political, it's just a matter of degree.

Thus banning political discussion channels (and in theory political dicussion) will just mean now you must split hairs about what's too political.

The issue isn't even the politics per se. It's poor behaviour. I believe that can be addressed by encouraging reporting, stiff penalties, and consistent consequences.

I know you disagree with that, which is why I left the admin team.

I still think it's worth a shot.

**Comment by snth** [comment] 2021-08-06 07:47
I also think that taking away controversial, non-tech channels would be a loss for the slack. I find people's opinions on zatech valuable/interesting because of their tech background so moving to a different platform would lose that filter.

Having been personally threatened on #politics recently, I didn't see the need to report the person. I felt enough people called out the behaviour that I assumed the person would reconsider their actions once out of the throws of their emotional state. 

Therefore I would be in favour of something like what @zeorin is proposing.

Is there a way to have a reaction emoji for a CoC violation? That might make it easier to flag offensive comments without disrupting the channel flow by calling "mods"? Also perhaps in response to those reactions a bot triggered post to the channel giving a 3 line summary of the consequences of CoC violations, similar to what we have in response to the mention of the term "guys". Part of the consequences could even be automated, like 1 flag => warning, 2 flags => kicked from channel, 3 flags => message to mods for review. Just brainstorming, not intending those particular consequences. Just trying to think of what would take the burden away from the mods and allow the community to moderate itself more effectively.

P.S. You might need thresholds on CoC reports to minimise the impact of bad actors.

**Comment by n1c** [comment] 2021-08-19 09:19
Yeah I've thought about an emoji-reaction thing a bit before. But generally we don't have any issues with getting reports of bad behaviour.

The root of the problem as I was [trying to say here](https://zatech.slack.com/archives/C1N2YMB4N/p1628076917093800) is that bad behaviour is often subjective. It's a really onerous task to try and resolve all the conflicts in a way that isn't just "ban person being reported". If we banned people based on reports then 80% of the most active users wouldn't be here.

We want all public channels to be safe places, and #covid/#politics/#politics-za have proven they can't do that. They are simultaneously _not_ technology related and responsible for a disproportionate amount of admin burden.

**Comment by mrMonkey2020** [comment] 2021-09-28 20:07
So may I politely ask if there was actually an outcome here? This process started on the 3rd of August its now the 28th of September, and speaking honestly and in a non confrontational manner the admin teams have not taken any clear and decisive action, if you have you have not communicated that back to the community. I've seen several requests about that, no timeframe has been given and the confrontation that I mentioned may happened by people being kicked happened. What is the course of action here?

**Comment by sixhobbits** [comment] 2021-09-29 12:56
So some updates here as a bunch of people are asking

* We have not made any final decisions or timelines on this yet. The general consensus seems to be that we will at some point close the inherently divisive channels and allow people to make individual private 'replacements', though there has been some minor drama about that too.
* For now, private channels have started to spring up and we have seen a lot more activity in these (we can see only aggregated stats of 'number of messages in public vs private channels'). This is good in some ways (a lower admin burden and a lot of the more uglier debates being hidden away), and bad in others (harder for more people to join a community if they can't easily discover it).
* Interestingly, things actually got *substantially* better from an admin point of view over the last couple of months, which is also why there has been slow progress on this and it has not been a priority for us. If starting up some private channels for more divisive behaviour turns out to be a solution and we continue to receive only very few reports or complaints from the so-called inherently divisive channels (and there is no definite list of which these include), then there is no real urgency to move ahead with the shutdown of the public channels.
* There are still a bunch of people engaging in name calling, very low-quality 'debate', and other kinds of conversation that are not in line with our code of conduct, but ultimately this is a Slack for the community and we take a "first, do no harm" approach wherever possible, so we have a strong "bias for inaction".

Probably not the timeline with gantt charts and cost estimates you all wanted, but that's what we have. We'll update as we can and welcome any more inputs here or in Slack (though probably try avoid rehashing what has already been said - you can use emoji's on any of the comments above if you agree).

**Comment by snth** [comment] 2021-09-29 13:37
Would be great if we can avoid the shutdown of the public channels. I hope the substantial reduction in calls for moderator action stays that way and we can keep the status quo.

**Comment by mrMonkey2020** [comment] 2021-10-30 07:36
```
Interestingly, things actually got substantially better from an admin point of view over the last couple of months, which is also why there has been slow progress on this and it has not been a priority for us. If starting up some private channels for more divisive behaviour turns out to be a solution and we continue to receive only very few reports or complaints from the so-called inherently divisive channels (and there is no definite list of which these include), then there is no real urgency to move ahead with the shutdown of the public channels.

There are still a bunch of people engaging in name calling, very low-quality 'debate', and other kinds of conversation that are not in line with our code of conduct, but ultimately this is a Slack for the community and we take a "first, do no harm" approach wherever possible, so we have a strong "bias for inaction".
```
These two things are clearly related. I've been speaking to members of the community who have rallied in the private channel complaining about purposeful inaction by the administrators. The approach of 'do no harm' is not really applying anymore. It is increasingly clear that through purposeful inaction the quality of the public channel has now dropped. A look at the channel between October 25-October 30 shows this. It's literally become a terrible place to be, and broadcasting that publicly and allowing it to continue for months on end while claiming to want to shut it down is duplicitous at best.

**Comment by fardarter** [comment] 2021-10-30 07:45
It was always a terrible place to be for people who didn't agree with you,
Malcolm. What's making it terrible for *you* right now is someone with a
different opinion not letting themselves be bullied into silence by the
right wing crew's continual insults.

**Comment by zkrige** [comment] 2021-10-30 10:38
>There are still a bunch of people engaging in name calling

Saul: immediately calls everyone who disagrees with him "right wing"

This comedy write itself

**Comment by mrMonkey2020** [comment] 2021-10-30 10:39
I'm not Malcolm but I'm advocating that *either* moderate it properly or shut it down at this point. The reason I held this so strongly is because admins don't really want to moderate it. It would be really distasteful that this thread starts echoing that channel.

**Comment by fardarter** [comment] 2021-10-30 11:57
Not Malcolm. Right.

**Comment by sixhobbits** [comment] 2021-11-01 10:19
@all - please don't post low effort comments here that do not add any value to the overall discussion - many of us receive email notifications for threads on here.

Please note that `#politics` `#politics-za` `#politics-conservatives` and `#politics-discussion` were closed today per the above.

**Closed by sixhobbits** 2021-11-01 10:19 UTC
